### ISSUE TITLE
circleci/python:2.7-node-browsers yarn path broke

### ISSUE THREAD

**Issue by lgonzalez-silen** [CircleCI-Public/circleci-dockerfiles#2]
we have been using this image for a while and all of a sudden yarn is not available.

looking inside of it, it's at /opt/yarn/yarn-v1.5.1

and there is a pretty useless symlink

/opt/yarn/yarn-v1.5.1 -> /opt/yarn-v1.5.1

it most likely should be

/opt/yarn -> /opt/yarn-v1.5.1

for easy pathing.

After fixing the symlink, yarn and which yarn return as expected.

**Comment by summera** [comment]
Also seeing this in `ruby:2.3.6-node-browsers`.
```
/bin/bash: yarn: command not found
```

Most likely related to: https://github.com/nodejs/docker-node/issues/649

**Comment by summera** [comment]
I think we are back in action now.

**Comment by ArturT** [comment]
@summera I see error for `ruby:2.5.0-node-browsers` as well. Probably other ruby images are affected as well. Did you fix it somehow or it just started working again? I tried to rebuild without cache but did not help.

```
/bin/bash: yarn: command not found
Exited with code 127
```

**Comment by brechin** [comment]
We're also still seeing this issue.

```
Build-agent version 0.0.4752-74e6083 (2018-03-15T15:19:52+0000)
Starting container circleci/python:2.7-stretch-node-browsers
  image cache not found on this host, downloading circleci/python:2.7-stretch-node-browsers
2.7-stretch-node-browsers: Pulling from circleci/python
...
Digest: sha256:1d3bd1ea82007b970e6a9d1d43d392d71dd383c26dd72112194a140c79588cff
Status: Downloaded newer image for circleci/python:2.7-stretch-node-browsers
  using image circleci/python@sha256:1d3bd1ea82007b970e6a9d1d43d392d71dd383c26dd72112194a140c79588cff
```

**Comment by summera** [comment]
@ArturT Just started working again. I didn't have to make any adjustments

**Comment by lgonzalez-silen** [comment]
It also started working for me.
