### ISSUE TITLE
Python images have no tar utility

### ISSUE THREAD

**Issue by toxuin** [CircleCI-Public/circleci-dockerfiles#4]
Whenever I try to use python image as a part of a workflow, I get following error:
`tar utility is not present in this image but it is required. Please install it to have workflow workspace capability.`

Am I doing it wrong? That image totally does have a `tar` executable, located at `/bin/tar`.

**Comment by eddiewebb** [comment]
Can you let me know what specific versions of python image (name and tag) you have tried?  Do you have a link to public build plan?

**Comment by toxuin** [comment]
Image tag would be `circleci/python:2.7-stretch-node`, build plan in not public, however I can tell you that problem was fixed by switching over to public `node:8.1.4` image and installing a python and the rest manually.

**Comment by ryanwohara** [comment]
I can't reproduce this at this time.
