### ISSUE TITLE
Build new image: Elixir 1.6.6 with Erlang 21.0 version

### ISSUE THREAD

**Issue by AndrewDryga** [CircleCI-Public/circleci-dockerfiles#8]

**Comment by ryanwohara** [comment]
You'd need to make that request against the Elixir community images. They're extending erlang:20 not 21 and we have no intention of creating our own Elixir images from scratch.

https://github.com/c0b/docker-elixir/blob/0936291249c7e11d4618a17a2b452045c9e6233a/1.6/Dockerfile
