### ISSUE TITLE
Install ZIP + PHP ZIP extension by default for php-node-browser images

### ISSUE THREAD

**Issue by wadmiraal** [CircleCI-Public/circleci-dockerfiles#9]
Hi,

Thanks for the great images, really helpful. We use them to run Selenium tests using [PHP Webdriver](https://github.com/facebook/php-webdriver). However, Webdriver requires the ZIP extension. Which means we install it "manually" at every test run, like so: 

````
sudo apt update && sudo apt install -y zlib1g-dev
sudo docker-php-ext-install zip
````

Which seems a bit wasteful; probably that many that use the `node-browsers` variant of the PHP images use either PHP Webdriver or Behat Mink for running tests, right? And we're spending minutes downloading and installing something, that probably is useful to many people. 

Would it be possible to consider installing these by default? I could open a PR if you wish, although I saw most `Dockerfiles` are generated automatically. How would I update them in order to satisfy a PR?

Thanks in advance!

**Comment by ryanwohara** [comment]
The images have finished publishing now. You can find the very latest Dockerfiles in the artifacts of this job:

https://circleci.com/gh/circleci/circleci-images/8197#artifacts/containers/0

**Comment by wadmiraal** [comment]
That's great news! Thanks a lot, I'll give it a spin immediately.

**Comment by wadmiraal** [comment]
Works great 👍 !
